local withTests = require('minitest')
local assert = require('luassert')

withTests(function(c)
    local split = require('split')
    c:describe("split",function(c)
        c:it("metafunction",function(c)
            assert.same(split,getmetatable('').split)
            assert.same(split,string.split)
        end)
        c:it("splitting",function (c)
            assert.same({'a b','c','d e','f'},string.split('a b  c  d e  f', "  "))
        end)
        c:it("magic",function(c)
            assert.same({'a b','c','d e','f'},("a b  c  d e  f"):split("  "))            
        end)
    end)
end)
